### ISSUE TITLE
missing 1 required positional argument: 'internal_parameters' in rawfile.py with Xyce

### ISSUE THREAD

**Issue by phsdv** [FabriceSalvaire/PySpice#150]
### Environment (OS, Python version, PySpice version, simulator)
Windows 7 64bit. Python 3.6.5 |Anaconda custom (64-bit)|, PySpive developkment brance(1.3.0), Xyce .10

### Expected Behaviour
show results

### Actual Behaviour
TypeError: __init__() missing 1 required positional argument: 'internal_parameters' in RawFile.py
```
2019-02-28 11:01:34,340 - PySpice.Spice.Netlist - Netlist.DEBUG - Element don't define a __pins__ attribute
2019-02-28 11:01:34,350 - PySpice.Spice.Netlist - Netlist.DEBUG - FixedPinElement don't define a __pins__ attribute
2019-02-28 11:01:34,351 - PySpice.Spice.Netlist - Netlist.DEBUG - SubCircuitElement don't define a __pins__ attribute
2019-02-28 11:01:34,355 - PySpice.Spice.Netlist - Netlist.DEBUG - Resistor don't define a __pins__ attribute
2019-02-28 11:01:34,358 - PySpice.Spice.Netlist - Netlist.DEBUG - SemiconductorResistor don't define a __pins__ attribute
2019-02-28 11:01:34,360 - PySpice.Spice.Netlist - Netlist.DEBUG - BehavioralResistor don't define a __pins__ attribute
2019-02-28 11:01:34,361 - PySpice.Spice.Netlist - Netlist.DEBUG - Capacitor don't define a __pins__ attribute
2019-02-28 11:01:34,363 - PySpice.Spice.Netlist - Netlist.DEBUG - SemiconductorCapacitor don't define a __pins__ attribute
2019-02-28 11:01:34,366 - PySpice.Spice.Netlist - Netlist.DEBUG - BehavioralCapacitor don't define a __pins__ attribute
2019-02-28 11:01:34,368 - PySpice.Spice.Netlist - Netlist.DEBUG - Inductor don't define a __pins__ attribute
2019-02-28 11:01:34,370 - PySpice.Spice.Netlist - Netlist.DEBUG - BehavioralInductor don't define a __pins__ attribute
2019-02-28 11:01:34,372 - PySpice.Spice.Netlist - Netlist.DEBUG - CoupledInductor don't define a __pins__ attribute
2019-02-28 11:01:34,373 - PySpice.Spice.Netlist - Netlist.DEBUG - VoltageControlledSwitch don't define a __pins__ attribute
2019-02-28 11:01:34,374 - PySpice.Spice.Netlist - Netlist.DEBUG - CurrentControlledSwitch don't define a __pins__ attribute
2019-02-28 11:01:34,376 - PySpice.Spice.Netlist - Netlist.DEBUG - VoltageSource don't define a __pins__ attribute
2019-02-28 11:01:34,377 - PySpice.Spice.Netlist - Netlist.DEBUG - CurrentSource don't define a __pins__ attribute
2019-02-28 11:01:34,378 - PySpice.Spice.Netlist - Netlist.DEBUG - VoltageControlledCurrentSource don't define a __pins__ attribute
2019-02-28 11:01:34,379 - PySpice.Spice.Netlist - Netlist.DEBUG - VoltageControlledVoltageSource don't define a __pins__ attribute
2019-02-28 11:01:34,383 - PySpice.Spice.Netlist - Netlist.DEBUG - CurrentControlledCurrentSource don't define a __pins__ attribute
2019-02-28 11:01:34,386 - PySpice.Spice.Netlist - Netlist.DEBUG - CurrentControlledVoltageSource don't define a __pins__ attribute
2019-02-28 11:01:34,388 - PySpice.Spice.Netlist - Netlist.DEBUG - BehavioralSource don't define a __pins__ attribute
2019-02-28 11:01:34,389 - PySpice.Spice.Netlist - Netlist.DEBUG - NonLinearVoltageSource don't define a __pins__ attribute
2019-02-28 11:01:34,390 - PySpice.Spice.Netlist - Netlist.DEBUG - NonLinearCurrentSource don't define a __pins__ attribute
2019-02-28 11:01:34,391 - PySpice.Spice.Netlist - Netlist.DEBUG - JunctionFieldEffectTransistor don't define a __pins__ attribute
2019-02-28 11:01:34,392 - PySpice.Spice.Netlist - Netlist.DEBUG - Mesfet don't define a __pins__ attribute
2019-02-28 11:01:34,393 - PySpice.Spice.Netlist - Netlist.DEBUG - LosslessTransmissionLine don't define a __pins__ attribute
2019-02-28 11:01:34,394 - PySpice.Spice.Netlist - Netlist.DEBUG - LossyTransmission don't define a __pins__ attribute
2019-02-28 11:01:34,394 - PySpice.Spice.Netlist - Netlist.DEBUG - CoupledMulticonductorLine don't define a __pins__ attribute
2019-02-28 11:01:34,395 - PySpice.Spice.Netlist - Netlist.DEBUG - SingleLossyTransmissionLine don't define a __pins__ attribute
2019-02-28 11:01:34,396 - PySpice.Spice.Netlist - Netlist.DEBUG - XSpiceElement don't define a __pins__ attribute
2019-02-28 11:01:34,397 - PySpice.Spice.Netlist - Netlist.DEBUG - GSSElement don't define a __pins__ attribute
2019-02-28 11:01:34,405 - PySpice.Spice.Netlist - Netlist.DEBUG - SinusoidalVoltageSource don't define a __pins__ attribute
2019-02-28 11:01:34,406 - PySpice.Spice.Netlist - Netlist.DEBUG - SinusoidalCurrentSource don't define a __pins__ attribute
2019-02-28 11:01:34,407 - PySpice.Spice.Netlist - Netlist.DEBUG - AcLine don't define a __pins__ attribute
2019-02-28 11:01:34,408 - PySpice.Spice.Netlist - Netlist.DEBUG - PulseVoltageSource don't define a __pins__ attribute
2019-02-28 11:01:34,409 - PySpice.Spice.Netlist - Netlist.DEBUG - PulseCurrentSource don't define a __pins__ attribute
2019-02-28 11:01:34,410 - PySpice.Spice.Netlist - Netlist.DEBUG - ExponentialVoltageSource don't define a __pins__ attribute
2019-02-28 11:01:34,411 - PySpice.Spice.Netlist - Netlist.DEBUG - ExponentialCurrentSource don't define a __pins__ attribute
2019-02-28 11:01:34,412 - PySpice.Spice.Netlist - Netlist.DEBUG - PieceWiseLinearVoltageSource don't define a __pins__ attribute
2019-02-28 11:01:34,413 - PySpice.Spice.Netlist - Netlist.DEBUG - PieceWiseLinearCurrentSource don't define a __pins__ attribute
2019-02-28 11:01:34,414 - PySpice.Spice.Netlist - Netlist.DEBUG - SingleFrequencyFMVoltageSource don't define a __pins__ attribute
2019-02-28 11:01:34,417 - PySpice.Spice.Netlist - Netlist.DEBUG - SingleFrequencyFMCurrentSource don't define a __pins__ attribute
2019-02-28 11:01:34,421 - PySpice.Spice.Netlist - Netlist.DEBUG - AmplitudeModulatedVoltageSource don't define a __pins__ attribute
2019-02-28 11:01:34,422 - PySpice.Spice.Netlist - Netlist.DEBUG - AmplitudeModulatedCurrentSource don't define a __pins__ attribute
2019-02-28 11:01:34,423 - PySpice.Spice.Netlist - Netlist.DEBUG - RandomVoltageSource don't define a __pins__ attribute
2019-02-28 11:01:34,424 - PySpice.Spice.Netlist - Netlist.DEBUG - RandomCurrentSource don't define a __pins__ attribute
2019-02-28 11:01:34,438 - PySpice.Spice.Xyce.Simulation.XyceCircuitSimulator - Simulation.DEBUG - desk
.title Thevenin Representation
Vinput 1 0 10V
Rgenerator 1 load 10Ohm
Rload load 0 1kOhm
.options TEMP = 25
.options TNOM = 25
.ic 
.op 
.end

2019-02-28 11:01:34,439 - PySpice.Spice.Xyce.Server.XyceServer - Server.INFO - Start the xyce subprocess
2019-02-28 11:01:34,512 - PySpice.Spice.Xyce.Server.XyceServer - Server.DEBUG - 

*****
***** Welcome to the Xyce(TM) Parallel Electronic Simulator
*****
***** This is version Xyce Release 6.10-opensource
***** Date: Thu Feb 28 11:01:34  2019


***** Executing netlist C:\Users\fg3zyt\AppData\Local\Temp\tmpzz9fatsm\input.cir

***** Reading and parsing netlist...
Netlist warning: No print specified
***** Setting up topology...

***** Device Count Summary ...
       R level 1 (Resistor)                   2
       V level 1 (Independent Voltage Source) 1
       ----------------------------------------
       Total Devices                          3
***** Setting up matrix structure...
***** Number of Unknowns = 3
***** Initializing...

------------------------------------------------------------
Operating point information:
Number of Independent Voltage Source models: 1
          name V level 1 (Independent Voltage Source)
          type                
         level               1

Number of Independent Voltage Source instances: 1
          name          VINPUT
         model V level 1 (Independent Voltage Source)
             TD              0
           DCV0             10
             PW              0
        ACPHASE              0
           FREQ              0
             V0              0
             TR              0
             V1              0
            PER              0
          ACMAG              0
            TD2              0
             V2              0
             TF              0
             VA              0
          THETA              0
          PHASE              0
   ACSOURCETYPE              6
            TD1              0
             FS              0
           TAU1              0
              T              0
           TAU2              0
             FC              0
            MDI              0
              R              0
              V              0
TRANSIENTSOURCETYPE              5
   DCSOURCETYPE              5
            NUM              0


Number of Resistor models: 1
          name R level 1 (Resistor)
          type                
         level               1
           TNOM             25
            TC1              0
            TC2              0
            TCE              0
            RSH              0
              R              1
           DEFW          1e-05

         NARROW              0

Number of Resistor instances: 2
          name      RGENERATOR          RLOAD
         model R level 1 (Resistor)R level 1 (Resistor)
              R             10           1000
            TC1              0              0
           TEMP             25             25
              M              1              1
              L              0              0
              W          1e-05          1e-05
            TC2              0              0
          DTEMP              0              0
            TCE              0              0

------------------------------------------------------------

***** Solution Summary *****
        Number Successful Steps Taken:          1
        Number Failed Steps Attempted:          0
        Number Jacobians Evaluated:             2
        Number Iteration Matrix Factorizations: 0
        Number Linear Solves:                   2
        Number Failed Linear Solves:            0
        Number Residual Evaluations:            3
        Number Nonlinear Convergence Failures:  0
        Total Residual Load Time:               2.00998e-05 seconds
        Total Jacobian Load Time:               5.33261e-06 seconds
        Total Linear Solution Time:             9.96787e-05 seconds


***** Total Simulation Solvers Run Time: 0.00228071 seconds
***** Total Elapsed Run Time:            0.00488959 seconds
*****
***** End of Xyce(TM) Simulation
*****

Timing summary of 1 processor
                 Stats                   Count       CPU Time              Wall Time
---------------------------------------- ----- --------------------- ---------------------
Xyce                                         1        0.015 (100.0%)        0.017 (100.0%)
  Analysis                                   1        0.000 ( 0.00%)        0.002 (13.17%)
    DC Sweep                                 1        0.000 ( 0.00%)        0.002 (13.03%)
      Solve                                  1        0.000 ( 0.00%)        0.000 ( 2.53%)
        Residual                             3        0.000 ( 0.00%)        0.000 ( 0.13%)
        Jacobian                             2        0.000 ( 0.00%)        0.000 ( 0.04%)
        Linear Solve                         2        0.000 ( 0.00%)        0.000 ( 0.61%)
      Successful Step                        1        0.000 ( 0.00%)        0.002 ( 9.74%)
  Netlist Import                             1        0.015 (100.0%)        0.001 ( 5.93%)
    Parse Context                            1        0.000 ( 0.00%)        0.000 ( 2.97%)
    Distribute Devices                       1        0.015 (100.0%)        0.000 ( 1.74%)
    Verify Devices                           1        0.000 ( 0.00%)        0.000 ( 0.04%)
    Instantiate                              1        0.000 ( 0.00%)        0.000 ( 0.64%)
  Late Initialization                        1        0.000 ( 0.00%)        0.001 ( 4.54%)
    Global Indices                           1        0.000 ( 0.00%)        0.000 ( 0.36%)
  Setup Matrix Structure                     1        0.000 ( 0.00%)        0.000 ( 0.96%)


2019-02-28 11:01:34,513 - PySpice.Spice.Xyce.Server.XyceServer - Server.WARNING - 
Netlist warning: No print specified
2019-02-28 11:01:34,523 - PySpice.Spice.Xyce.RawFile.RawFile - RawFile.DEBUG - 
Title: .title Thevenin Representation
Date: Thu Feb 28 11:01:34 2019
Plotname: DC transfer characteristic
Flags: real
No. Variables: 4
No. Points: 1                 
Variables:
        0       sweep   voltage
        1       V(1)    voltage
        2       LOAD    voltage
        3       VINPUT#branch   current
Binary:

2019-02-28 11:01:34,527 - PySpice.Spice.Xyce.RawFile.RawFile - RawFile.DEBUG - Title: .title Thevenin Representation
2019-02-28 11:01:34,529 - PySpice.Spice.Xyce.RawFile.RawFile - RawFile.DEBUG - Date: Thu Feb 28 11:01:34 2019
2019-02-28 11:01:34,530 - PySpice.Spice.Xyce.RawFile.RawFile - RawFile.DEBUG - Plotname: DC transfer characteristic
2019-02-28 11:01:34,532 - PySpice.Spice.Xyce.RawFile.RawFile - RawFile.DEBUG - Flags: real
2019-02-28 11:01:34,536 - PySpice.Spice.Xyce.RawFile.RawFile - RawFile.DEBUG - No. Variables: 4
2019-02-28 11:01:34,537 - PySpice.Spice.Xyce.RawFile.RawFile - RawFile.DEBUG - No. Points: 1                 
2019-02-28 11:01:34,538 - PySpice.Spice.Xyce.RawFile.RawFile - RawFile.DEBUG - Variables:
2019-02-28 11:01:34,538 - PySpice.Spice.Xyce.RawFile.RawFile - RawFile.DEBUG -  0       sweep   voltage
2019-02-28 11:01:34,539 - PySpice.Spice.Xyce.RawFile.RawFile - RawFile.DEBUG -  1       V(1)    voltage
2019-02-28 11:01:34,539 - PySpice.Spice.Xyce.RawFile.RawFile - RawFile.DEBUG -  2       LOAD    voltage
2019-02-28 11:01:34,540 - PySpice.Spice.Xyce.RawFile.RawFile - RawFile.DEBUG -  3       VINPUT#branch   current
Traceback (most recent call last):

  File "<ipython-input-1-07cd938e0c8e>", line 1, in <module>
    runfile('C:/Users/fg3zyt/Documents/Scripts/CalcTools/thevenin-norton-theorem.py', wdir='C:/Users/fg3zyt/Documents/Scripts/CalcTools')

  File "C:\progs\Miniconda3\envs\tools\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\progs\Miniconda3\envs\tools\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/fg3zyt/Documents/Scripts/CalcTools/thevenin-norton-theorem.py", line 73, in <module>
    analysis = simulator.operating_point()

  File "C:\progs\Miniconda3\envs\tools\lib\site-packages\PySpice\Spice\Simulation.py", line 729, in operating_point
    return self._run('operating_point', *args, **kwargs)

  File "C:\progs\Miniconda3\envs\tools\lib\site-packages\PySpice\Spice\Xyce\Simulation.py", line 73, in _run
    return raw_file.to_analysis()

  File "C:\progs\Miniconda3\envs\tools\lib\site-packages\PySpice\Spice\RawFile.py", line 303, in to_analysis
    return self._to_dc_analysis()

  File "C:\progs\Miniconda3\envs\tools\lib\site-packages\PySpice\Spice\Xyce\RawFile.py", line 177, in _to_dc_analysis
    return super()._to_dc_analysis(sweep_variable)

  File "C:\progs\Miniconda3\envs\tools\lib\site-packages\PySpice\Spice\RawFile.py", line 342, in _to_dc_analysis
    branches=self.branches(),

TypeError: __init__() missing 1 required positional argument: 'internal_parameters'
```

### Steps to reproduce the behaviour
run the following code (from examples):
Note, also transient analysis has similar behavior.
```
import PySpice.Logging.Logging as Logging
logger = Logging.setup_logging()

####################################################################################################

from PySpice.Spice.Netlist import Circuit
from PySpice.Unit import *

####################################################################################################

thevenin_circuit = Circuit('Thevenin Representation')

thevenin_circuit.V('input', 1, thevenin_circuit.gnd, 10@u_V)
thevenin_circuit.R('generator', 1, 'load', 10@u_Ω)
thevenin_circuit.R('load', 'load', thevenin_circuit.gnd, 1@u_kΩ)

simulator = thevenin_circuit.simulator(simulator='xyce-serial', temperature=25, nominal_temperature=25)
simulator._spice_server._xyce_command = "C:\\progs\\Xyce 6.10 OPENSOURCE\\bin\\Xyce.exe"
analysis = simulator.operating_point()

load_node = analysis.load
print('Node {}: {:5.2f} V'.format(str(load_node), float(load_node)))
#o#
```

**Comment by FabriceSalvaire** [comment]
I cannot reproduce this issue with v1.3.1
