### ISSUE TITLE
pip install from github fails

### ISSUE THREAD

**Issue by rbarzic** [FabriceSalvaire/PySpice#185]
### Environment (OS, Python version, PySpice version, simulator)
Ubuntu 18.04.3
Python 3.8.8
PySpice : master branch

### Expected Behaviour
pip install git+https://github.com/FabriceSalvaire/PySpice should install the latest version

### Actual Behaviour
Collecting git+https://github.com/FabriceSalvaire/PySpice
  Cloning https://github.com/FabriceSalvaire/PySpice to /tmp/pip-req-build-dnnt3z4t
  Running command git clone -q https://github.com/FabriceSalvaire/PySpice /tmp/pip-req-build-dnnt3z4t
    ERROR: Command errored out with exit status 1:
     command: /home/ronan/.virtualenvs/test_pip/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-dnnt3z4t/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-dnnt3z4t/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-dnnt3z4t/pip-egg-info
         cwd: /tmp/pip-req-build-dnnt3z4t/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-dnnt3z4t/setup.py", line 50, in <module>
        exec(compile(open('setup_data.py').read(), 'setup_data.py', 'exec'))
      File "setup_data.py", line 35, in <module>
        with open(init_path) as fh:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-dnnt3z4t/PySpice/__init__.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

### Steps to reproduce the behaviour

pip install git+https://github.com/FabriceSalvaire/PySpice

pip install https://github.com/FabriceSalvaire/PySpice/archive/v1.2.zip works without issue
pip install git+https://github.com/FabriceSalvaire/PySpice.git@v1.2 works also

On a side note, versions above 1.2 have no tag in github

**Comment by rbarzic** [comment]
Apparently, direct installation from github is no longer possible. Project needs to be cloned locally
invoke needs to be installed and the following command is needed :
invoke release.update-git-sha
then the installation can proceed with "pip install ."
