### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Ricky-PV** [FabriceSalvaire/PySpice#195]
I've been trying to get pyspice up and running without success. Is anyone able to spot the issue?

### Expected Behaviour
Run a simple SPICE simulation

### Actual Behaviour
Following error is returned:
runfile('C:/everything/Spice_simulations/20200422-full-model/untitled0.py', wdir='C:/everything/Spice_simulations/20200422-full-model')
C:\Users\username\AppData\Local\Continuum\anaconda3\envs\pvmismatch-env\lib\site-packages\PySpice\Logging\Logging.py:47: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  logging_config = yaml.load(open(logging_config_file_name, 'r'))
Traceback (most recent call last):

  File "<ipython-input-4-2f94ee77b6cd>", line 1, in <module>
    runfile('C:/everything/Spice_simulations/20200422-full-model/untitled0.py', wdir='C:/everything/Spice_simulations/20200422-full-model')

  File "C:\Users\username\AppData\Local\Continuum\anaconda3\envs\pvmismatch-env\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\username\AppData\Local\Continuum\anaconda3\envs\pvmismatch-env\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/everything/Spice_simulations/20200422-full-model/untitled0.py", line 27, in <module>
    simulator = circuit.simulator(temperature=25, nominal_temperature=25)

  File "C:\Users\username\AppData\Local\Continuum\anaconda3\envs\pvmismatch-env\lib\site-packages\PySpice\Spice\Netlist.py", line 1281, in simulator
    return CircuitSimulator.factory(self, *args, **kwargs)

  File "C:\Users\username\AppData\Local\Continuum\anaconda3\envs\pvmismatch-env\lib\site-packages\PySpice\Spice\Simulation.py", line 708, in factory
    return sub_cls(circuit, *args, **kwargs)

  File "C:\Users\username\AppData\Local\Continuum\anaconda3\envs\pvmismatch-env\lib\site-packages\PySpice\Spice\NgSpice\Simulation.py", line 99, in __init__
    self._ngspice_shared = NgSpiceShared.new_instance()

  File "C:\Users\username\AppData\Local\Continuum\anaconda3\envs\pvmismatch-env\lib\site-packages\PySpice\Spice\NgSpice\Shared.py", line 331, in new_instance
    instance = cls(ngspice_id=ngspice_id, send_data=send_data)

  File "C:\Users\username\AppData\Local\Continuum\anaconda3\envs\pvmismatch-env\lib\site-packages\PySpice\Spice\NgSpice\Shared.py", line 349, in __init__
    self._load_library()

  File "C:\Users\username\AppData\Local\Continuum\anaconda3\envs\pvmismatch-env\lib\site-packages\PySpice\Spice\NgSpice\Shared.py", line 375, in _load_library
    self._ngspice_shared = ffi.dlopen(library_path)

  File "C:\Users\username\AppData\Local\Continuum\anaconda3\envs\pvmismatch-env\lib\site-packages\cffi\api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)

  File "C:\Users\username\AppData\Local\Continuum\anaconda3\envs\pvmismatch-env\lib\site-packages\cffi\api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)

  File "C:\Users\username\AppData\Local\Continuum\anaconda3\envs\pvmismatch-env\lib\site-packages\cffi\api.py", line 827, in _load_backend_lib
    raise OSError(msg)

OSError: cannot load library 'C:\Program Files\Spice64_dll\dll-vs\ngspice.dll': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Program Files\\Spice64_dll\\dll-vs\\ngspice.dll'

### Steps to reproduce the behaviour
The installation instructions were followed. ngspice v 30 was downloaded and unzipped in the specified directory. Windows explorer shows that the file does exist with the following path:
C:\Program Files\Spice64-dll\dll-vs\ngspice.dll

Code:
`import matplotlib.pyplot as plt
####################################################################################################
import PySpice.Logging.Logging as Logging
logger = Logging.setup_logging()
####################################################################################################
from PySpice.Doc.ExampleTools import find_libraries
from PySpice.Probe.Plot import plot
from PySpice.Spice.Library import SpiceLibrary
from PySpice.Spice.Netlist import Circuit
from PySpice.Unit import *
####################################################################################################
from PySpice.Spice.NgSpice.Shared import NgSpiceShared
####################################################################################################
libraries_path = find_libraries()
spice_library = SpiceLibrary(libraries_path)

circuit = Circuit('test')

r1 = circuit.R('1', 1, 0, 10)
simulator = circuit.simulator(temperature=25, nominal_temperature=25)`

**Comment by FabriceSalvaire** [comment]
> did not manage to locate a library called 'C:\Program Files\Spice64_dll\dll-vs\ngspice.dll'

typo _ and not -

> C:\Program Files\Spice64-dll\dll-vs\ngspice.dll
