### ISSUE TITLE
Install from source instructions not working

### ISSUE THREAD

**Issue by follo** [FabriceSalvaire/PySpice#197]
### Environment (OS, Python version, PySpice version, simulator)
Linux, Python 3.7
### Expected Behaviour
Installed software
### Actual Behaviour
Error message
> python setup.py build
Traceback (most recent call last):
  File "setup.py", line 50, in <module>
    exec(compile(open('setup_data.py').read(), 'setup_data.py', 'exec'))
  File "setup_data.py", line 35, in <module>
    with open(init_path) as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'PySpice/__init__.py'
### Steps to reproduce the behaviour
Follow the instructions on https://pyspice.fabrice-salvaire.fr/installation.html#installation-page
In essense:
git clone https://github.com/FabriceSalvaire/PySpice.git
python setup.py build # <--- FAILS!
python setup.py install

**Comment by FabriceSalvaire** [comment]
PySpice loads the file `PySpice/__init__.py` why the hell __ are gone ???
