### ISSUE TITLE
Pulling NgSpice dependency does not work

### ISSUE THREAD

**Issue by leonhardpet** [FabriceSalvaire/PySpice#275]
### Environment (OS, Python version, PySpice version, simulator)
Windows 10
Python 3.7.4
PySpice 1.4.3

### Expected Behaviour
pyspice-post-installation.exe --install-ngspice-dll
is expected to install the NgSpice DLL

### Actual Behaviour
pyspice-post-installation.exe --install-ngspice-dll
crashes with following error:
Get https://sourceforge.net/projects/ngspice/files/ng-spice-rework/32/ngspice-32_dll_64.zip ... -> C:\Users\<user>\AppData\Local\Temp\1\tmp7uabhkeg\ngspice-32_dll_64.zip
Traceback (most recent call last):
  File "c:\users\<user>\appdata\local\continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\<user>\appdata\local\continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\<user>\AppData\Roaming\Python\Python37\Scripts\pyspice-post-installation.exe\__main__.py", line 9, in <module>
  File "C:\Users\<user>\AppData\Roaming\Python\Python37\site-packages\PySpice\Scripts\pyspice_post_installation.py", line 452, in main
    return _.run()
  File "C:\Users\<user>\AppData\Roaming\Python\Python37\site-packages\PySpice\Scripts\pyspice_post_installation.py", line 160, in run
    self.install_ngspice_dll()
  File "C:\Users\<user>\AppData\Roaming\Python\Python37\site-packages\PySpice\Scripts\pyspice_post_installation.py", line 213, in install_ngspice_dll
    self._donwload_file(url, zip_path)
  File "C:\Users\<user>\AppData\Roaming\Python\Python37\site-packages\PySpice\Scripts\pyspice_post_installation.py", line 183, in _donwload_file
    assert(response.status_code == requests.codes.ok)
AssertionError

### Steps to reproduce the behaviour
Execute pyspice-post-installation.exe --install-ngspice-dll

**Comment by FabriceSalvaire** [comment]
should be fixed in devel branch PR #270
