### ISSUE TITLE
Fix devel branch

### ISSUE THREAD

**Issue by FabriceSalvaire** [FabriceSalvaire/PySpice#90]
```
2017-11-23 17:05:55,180 - PySpice.Spice.NgSpice.Simulation.NgSpiceSharedCircuitSimulator._run - DEBUG - ['const']
Traceback (most recent call last):
  File "/home/fabrice/home/developpement/python/PySpice/examples/diode/diode-characteristic-curve.py", line 112, in <module>
    analysis = simulator.dc(Vinput=slice(-2, 5, .01))
  File "/home/fabrice/PySpice/PySpice/Spice/Simulation.py", line 712, in dc
    return self._run('dc', *args, **kwargs)
  File "/home/fabrice/PySpice/PySpice/Spice/NgSpice/Simulation.py", line 122, in _run
    return self._ngspice_shared.plot(self, plot_name).to_analysis()
  File "/home/fabrice/PySpice/PySpice/Spice/NgSpice/Shared.py", line 1070, in plot
    plot[vector_name] = Vector(vector_name, vector_type, array)
  File "/home/fabrice/PySpice/PySpice/Spice/NgSpice/Shared.py", line 106, in __init__
    self._unit = NgSpiceShared.__type_to_unit__[type_]
KeyError: no_type
```

**Comment by FabriceSalvaire** [comment]
all examples work in fe4d9b5
